In [4]:
import numpy as np
from scipy.linalg import lu

# Define the matrix from the image provided
A = np.array([[9, 2, -1],
              [3, 7, 2],
              [2, 3, 8]], dtype=float)

# Perform LU decomposition with permutation
P, L, U = lu(A)  # 'permute_l' flag is not needed here

# Check that L * U equals the original matrix A
A_reconstructed = np.dot(L, U)

# Calculate the determinant using LU decomposition
# The determinant of A is the product of the diagonal elements of U
det_A = np.prod(np.diag(U))

print('L:', L)
print('U:', U)
print('A reconstructed:', A_reconstructed)
print('Determinant of A:', det_A)


L: [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.22222222 0.40350877 1.        ]]
U: [[ 9.          2.         -1.        ]
 [ 0.          6.33333333  2.33333333]
 [ 0.          0.          7.28070175]]
A reconstructed: [[ 9.  2. -1.]
 [ 3.  7.  2.]
 [ 2.  3.  8.]]
Determinant of A: 414.99999999999994
